version: "3.8"

services:
  server:
    image: golang:1.25
    command: |
      bash -c "
      apt update && apt install -y ffmpeg && sleep infinity
      "
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspaces:cached

    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: videodb
      REDIS_ADDR: redis:6379
      S3_ENDPOINT: host.docker.internal:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_BUCKET: videos
      S3_USE_SSL: false
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - video-net
  client:
    image: oven/bun:latest
    command: |
      bash -c "
      apt update && apt install -y git && sleep infinity
      "
    volumes:
      - ..:/workspaces:cached
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - video-net

networks:
  video-net:
    driver: bridge
    external: true
    name: devcontainer_default
